services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    worker:
        build: ./worker
        depends_on:
            - redis
        command: python worker.py
        environment:
            PYTHONUNBUFFERED: 1
            REDIS_HOST: redis